name: Auto Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Increment patch version
        id: bump_version
        run: |
          IFS='.' read -r major minor patch <<< "${LATEST_TAG#v}"
          new_version="$major.$minor.$((patch + 1))"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag "v${NEW_VERSION}"
          git push origin "v${NEW_VERSION}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          body: "🚀 Nuevo release generado automáticamente."
          draft: false
          prerelease: false
        env:

          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Usa el PAT en lugar de GITHUB_TOKEN
